import Json_Handling as JH

Entry_map = {"rangedwarfare": "YourStats,Ranged,RangedWarfare",
             "rangednumberofshots": "YourStats,Ranged,NumberOfShots",
             "rangednumberofdice": "YourStats,Ranged,NumberOfDice",
             "rangedsizeofdice": "YourStats,Ranged,SizeOfDice",
             "rangedaddeddamage": "YourStats,Ranged,AddedDamage",
             "rangedpierce": "YourStats,Ranged,Pierce",
             "roundsinweapon": "YourStats,Ranged,RoundsInWeapon",
             "vehiclehitlocation": "YourStats,VehicleHitLocation",
             "meleewarfare": "YourStats,Melee,MeleeWarfare",
             "meleestrikes": "YourStats,Melee,MeleeStrikes",
             "meleenumberofdice": "YourStats,Melee,NumberOfDice",
             "meleesizeofdice": "YourStats,Melee,SizeOfDice",
             "meleeaddeddamage": "YourStats,Melee,AddedDamage",
             "meleepierce": "YourStats,Melee,Pierce",
             "enemyahead": "EnemyStats,Enemy,Armor,Head",
             "enemyaarm": "EnemyStats,Enemy,Armor,Arm",
             "enemyachest": "EnemyStats,Enemy,Armor,Chest",
             "enemyaleg": "EnemyStats,Enemy,Armor,Leg",
             "enemyagility": "EnemyStats,Enemy,Agility",
             "enemydebuff": "EnemyStats,Enemy,AgilityDebuffInvunerability",
             "enemytoughness": "EnemyStats,Enemy,ToughnessModifier",
             "vehiclearmor": lambda: f"EnemyStats,Vehicle,Armor,{JH.read("Saved_Stats.json")["YourStats"]["VehicleHitLocation"]}",
             "vehiclemanuverability": "EnemyStats,Vehicle,Manuverability",
             "vehicledebuff": "EnemyStats,Vehicle,ManuverabilityDebuffInvunerability",
             "vehicletoughness": "EnemyStats,Vehicle,ToughnessModifier"}

Prefernce_map = {"darkmode": "Settings,DarkMode",
                 "tooltip": "Settings,ToolTips",
                 "resetentries": "Settings,ResetEntriesOnOpen",
                 "penetrating": "SpecialRules,Penetrating,Active",
                 "diceminimuma": "SpecialRules,DiceMinimum,Active",
                 "diceminimumv": "SpecialRules,DiceMinimum,Value",
                 "hardlight": "SpecialRules,HardLight,Active",
                 "headshot": "SpecialRules,HeadShot,Active",
                 "assassination": "SpecialRules,Assassination,Active"}